### ISSUE TITLE
plz2add readme

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/maybe-dotnet#1]
So that the project is grok-ready to the lay person.

**Comment by allan-stewart** [comment]
So... this was a long time in coming, but there is a readme file now. Take a look and let us know if you think there is anything else we should add before we close this issue.

**Comment by Insomniak47** [comment]
Might wanna grab the typo: Annonymous -> Anonymous

**Comment by allan-stewart** [comment]
Got the typo; thanks @Insomniak47 .

I think I'm gonna go ahead and close this issue now since it appears to be resolved.
